# Generated by Django 6.0.6 on 2026-06-27 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Church Leader Certificate', 'verbose_name_plural': 'Church Leader Certificates'},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='course_name',
        ),
        migrations.AddField(
            model_name='certificate',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Any additional notes or remarks', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='church_district',
            field=models.CharField(blank=True, default='Main District', help_text='District/Conference', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='church_location',
            field=models.CharField(default='SDA Church', help_text='City/Town where church is located', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='church_name',
            field=models.CharField(default='Seventh-day Adventist Church', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='other_position',
            field=models.CharField(blank=True, help_text="If 'Other' position selected", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='position',
            field=models.CharField(choices=[('PASTOR', 'Pastor'), ('ELDER', 'Church Elder'), ('DEACON', 'Deacon'), ('DEACONESS', 'Deaconess'), ('DEPARTMENT_LEADER', 'Department Leader'), ('SABBATH_SCHOOL_SUPERINTENDENT', 'Sabbath School Superintendent'), ('YOUTH_LEADER', 'Youth Leader'), ('CHOIR_DIRECTOR', 'Choir Director'), ('COMMUNICATION_LEADER', 'Communication Leader'), ('STEWARDSHIP_LEADER', 'Stewardship Leader'), ('PRAYER_LEADER', 'Prayer Leader'), ('MUSIC_DIRECTOR', 'Music Director'), ('OTHER', 'Other')], default='PASTOR', max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='scripture_reference',
            field=models.CharField(blank=True, default='Isaiah 40:31', help_text='Bible verse for certificate', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='service_duration_years',
            field=models.IntegerField(default=1, help_text='Number of years in service/leadership'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='service_end_date',
            field=models.DateField(blank=True, help_text='End date (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='service_start_date',
            field=models.DateField(default=datetime.date.today, help_text='Date when service/leadership started'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signed_by',
            field=models.CharField(default='Pastor', help_text='Name of person signing', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signed_by_church',
            field=models.CharField(blank=True, help_text='Church/Organization of signer', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signed_by_title',
            field=models.CharField(default='Head Pastor', help_text='Title of person signing', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='full_name',
            field=models.CharField(help_text='Full name of the church leader', max_length=200),
        ),
    ]
