# Generated by Django 6.0.6 on 2026-06-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='church_district',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='church_location',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='church_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='scripture_reference',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='service_duration_years',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='service_end_date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='service_start_date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='signed_by',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='signed_by_church',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='signed_by_title',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_pdf',
            field=models.TextField(blank=True, help_text='Base64 encoded certificate PDF - complete certificate stored here', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='heading',
            field=models.CharField(default='SEVENTH-DAY ADVENTIST CHURCH', help_text='Main heading displayed at top center between logo and person image', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='leader_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded signature of the church leader - displayed at bottom-right', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='logo_image',
            field=models.TextField(blank=True, help_text='Base64 encoded logo image - displayed at top-left corner', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='person_image',
            field=models.TextField(blank=True, help_text='Base64 encoded person/recipient image - displayed at top-right corner', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='person_name',
            field=models.CharField(default='Name', help_text='Full name of the certificate recipient - displayed prominently in center', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signature_person',
            field=models.TextField(blank=True, help_text='Base64 encoded signature of the person - displayed at bottom-left', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='working_time',
            field=models.CharField(default='5 years', help_text="Duration of service - displayed below position (e.g., '5 years', '3 months')", max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Any additional notes or remarks - displayed below working time', null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='position',
            field=models.CharField(choices=[('PASTOR', 'Pastor'), ('ELDER', 'Church Elder'), ('DEACON', 'Deacon'), ('DEACONESS', 'Deaconess'), ('DEPARTMENT_LEADER', 'Department Leader'), ('SABBATH_SCHOOL_SUPERINTENDENT', 'Sabbath School Superintendent'), ('YOUTH_LEADER', 'Youth Leader'), ('CHOIR_DIRECTOR', 'Choir Director'), ('COMMUNICATION_LEADER', 'Communication Leader'), ('STEWARDSHIP_LEADER', 'Stewardship Leader'), ('PRAYER_LEADER', 'Prayer Leader'), ('MUSIC_DIRECTOR', 'Music Director'), ('OTHER', 'Other')], default='PASTOR', help_text='Position/role of the person - displayed below person name', max_length=50),
        ),
    ]
