# Generated by Django 6.0.6 on 2026-07-05 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_remove_certificate_id_certificate_certificate_id_and_more'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='person_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='members.member'),
        ),
    ]
