# Generated by Django 6.0.6 on 2026-07-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='member',
        ),
    ]
