# Generated by Django 6.0.6 on 2026-07-06 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0002_remove_history_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-event_date'], 'verbose_name': 'History', 'verbose_name_plural': 'Histories'},
        ),
        migrations.AddField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='history_image',
            field=models.TextField(blank=True, help_text='Base64 encoded image of the history event', null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='title',
            field=models.CharField(default='Untitled', help_text='Title of the history event', max_length=255),
        ),
        migrations.AddField(
            model_name='history',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='event_date',
            field=models.DateField(help_text='Date when the event occurred'),
        ),
        migrations.AlterField(
            model_name='history',
            name='event_description',
            field=models.TextField(help_text='Description of the event'),
        ),
        migrations.AlterField(
            model_name='history',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the event', null=True),
        ),
        migrations.AlterModelTable(
            name='history',
            table='history',
        ),
    ]
