# Generated by Django 6.0.6 on 2026-07-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='assigned_by',
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
