# Generated by Django 6.0.6 on 2026-07-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_remove_userrole_assigned_by_alter_userrole_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='role',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='role',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
