# Generated by Django 6.0.6 on 2026-07-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_remove_role_description_remove_role_permissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='email',
            field=models.EmailField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('pastor', 'Pastor'), ('elder', 'Elder'), ('deacon', 'Deacon')], max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='role',
            table=None,
        ),
    ]
